config/routes.rb
Minimal::Application.routes.draw do
  root :to => "pages#home"

  get :home, :to => "pages#home"

  scope :module => :dashboard do
    resources :posts, :except => [:index, :show]
  end

  # auth
  scope :module => :auth do

    get   :login,   :to => "sessions#new"
    post  :login,   :to => "sessions#create"
    match :logout,  :to => "sessions#destroy"

    resources :password_resets do
      collection do
        match :confirmation
      end
    end

    resources :registrations

  end


  resources :users, :only => [:index, :show]
  resources :posts, :only => :show

end

app/models/post.rb
class Post < ActiveRecord::Base

  acts_as_nested_set

  attr_accessible :body, :title, :parent_id

  belongs_to :user
  validates :body, :presence => true

  after_create :mail_parent

  default_scope :order => "created_at DESC"

  def mail_parent
    PostMailer.replied_at(self).deliver if child?
  end

end

app/models/user.rb
class User < ActiveRecord::Base

  attr_accessible :email, :password, :password_confirmation, :username

  authenticates_with_sorcery!

  has_many :posts

  before_validation :trim_and_downcase_username, :on => :create

  username_regex = /\A[A-Za-z0-9_]+\z/
  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates_presence_of :username
  validates_length_of :username, :maximum => 32
  validates_format_of :username, :with => username_regex 
  validates_uniqueness_of :username, :case_sensitive => false

  validates_uniqueness_of :email, :case_senstive => false
  validates_presence_of :email
  validates_format_of :email, :with => email_regex

  validates_length_of :password, :minimum => 6, :message => "must be at least 6 characters long", :if => :password

  private

    def trim_and_downcase_username
      if username.present?
        username.strip!
        username.downcase!
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :get_writers

  def get_writers
    @writers ||= User.order("updated_at DESC").all
  end
end

app/controllers/dashboard/posts_controller.rb
class Dashboard::PostsController < ApplicationController
  before_filter :require_login
  before_filter :is_allowed?, :only => [:edit, :update, :destroy]

  def new
    @post = Post.new
    @post.parent = Post.find(params[:respond]) if params.key? :respond
  end

  def create
    if @post = current_user.posts.create(params[:post])
      current_user.touch
      redirect_to @post, :alert => "Nice. New post."
    else
      render :action => :edit
    end
  end

  def edit

  end

  def update
    @post.update_attributes(params[:post])
    redirect_to @post
  end

  def destroy
    @post.destroy
    redirect_to current_user
  end

  private

    def is_allowed?
      @post = Post.find(params[:id])
      redirect_to(current_user, :alert => "You can't do that...") unless current_user = @post.user
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @posts = Post.order("created_at DESC").page(params[:page]).per(20)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page params[:page]
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard/posts_helper.rb
module Dashboard::PostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_error_messages.html.haml
- if object.errors.any?
  %ul#errors
    - object.errors.full_messages.each do |message|
      %li= message

app/views/common/_flash_messages.html.haml
- flash.each do |key, value|
  %div{:class => "flash #{key}"}= value

app/views/common/_footer.html.haml
#footer
  .container.clearfix
    .two-col
      #copyright © Spinlister 2011
      %nav
        %ul
          %li= link_to 'about', about_path
          %li= link_to 'jobs', "http://blog.spinlister.com/post/11624000913/hustlers-please-apply"
          %li= link_to 'terms', terms_path
          %li= link_to 'privacy', privacy_path
          %li= link_to 'blog', "http://blog.spinlister.com"
          %li= link_to 'contact', "mailto:hello@spinlister.com"
    .one-col
      #social-nav
        %nav
          %ul
            %li
              = link_to "http://facebook.com/spinlister" do
                .facebook facebook
- if Rails.env.production?
  :javascript
  
    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-18799247-5']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  

app/views/dashboard/posts/_form.html.haml
#editor
  = form_for @post do |f|
    = f.hidden_field :parent_id
    .fields
      - if @post.parent.nil?
        .field
          = f.label :title
          %br/
          = f.text_field :title
      - else
        %strong
          in response to
          = @post.parent.title

      .field
        = f.label :body
        %br/
        = f.text_area :body
      = f.submit "Save"

app/views/dashboard/posts/edit.html.haml
= render 'form'

app/views/dashboard/posts/new.html.haml
= render "form"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Minimal
    = stylesheet_link_tag    "application"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    %header.clearfix
      %ul.clearfix
        %li.title
          = link_to "postrface", root_path
        %li= link_to "write", new_post_path
        - if logged_in?
          %li= link_to "me", current_user
          %li= link_to "logout", logout_path
        - else
          %li= link_to "login", login_path
      %ul#writers
        - for writer in @writers
          - if writer.posts.any?
            %li
              = link_to writer do
                %span.username= writer.username
                %span.postname= writer.posts.first.title
    %section#content
      = yield

app/views/pages/home.html.haml
#posts
  = render :partial => "posts/post", :collection => @posts, :locals => {:with_username => true}
  = paginate @posts

app/views/posts/_post.html.haml
.post
  %h2
    = link_to post do
      %span.title
        - if post.root?
          = post.title
        - else
          = post.root.title
      - if with_username
        %span.username
          - if post.root?
            &larr;
          - else
            &crarr;
          = post.user.username
  = simple_format post.body
  %p
    - if logged_in? and post.user == current_user
      = link_to "edit", edit_post_path(post)

app/views/posts/show.html.haml
%h1.back= link_to "#{@post.user.username}", @post.user
= render :partial => "post", :object => @post, :locals => {:with_username => false}
- if logged_in?
  %p
    = link_to new_post_path(:respond => @post.id) do
      &crarr; respond
- for post in @post.children
  = render :partial => "post", :object => post, :locals => {:with_username => true}

app/views/users/index.html.haml
#users
  - for user in @users
    .user
      = link_to user.username, user
      - if user.posts.blank?
        has not written yet
      - else
        - post = user.posts.first
        wrote
        = link_to post.title, post
        = time_ago_in_words post.created_at
        ago

app/views/users/show.html.haml
%h1= @user.username

#posts
  = render :partial => "posts/post", :collection => @posts, :locals => {:with_username => false}
  = paginate @posts
  - if logged_in? and @user == current_user and @posts.blank?
    You have no posts yet.